kind: pipeline
name: parallel-requests

steps:
  - name: parallel-requests-test
    pull: if-not-exists
    image: python:3.7
    commands:
      - pip install invoke
      - inv install
      - inv check